#!/bin/bash
# run_ragtruth_all.sh
# Run TSV on RAGTruth dataset: 1 detection model × 3 task types
#
# Detection model: Meta-Llama-3.1-8B-Instruct (extracts hidden states for TSV)
# Data source: RAGTruth responses generated by llama-2-7b-chat
#
# Usage: bash run_ragtruth_all.sh

set -e

# ============================================
# Configuration
# ============================================
DETECTION_MODEL="qwen3-8B"                      # Key in HF_NAMES → /gz-fs/models/Meta-Llama-3.1-8B-Instruct
RAGTRUTH_DIR="../../data/RAGTruth/dataset"
DATA_MODEL="llama-2-7b-chat"                       # RAGTruth response model filter
BATCH_SIZE=1
STR_LAYER=9
LAM=5
LR=0.005
COS_TEMP=0.1
EMA_DECAY=0.99
INIT_EPOCHS=20
AUG_EPOCHS=20
NUM_EXEMPLARS=32
NUM_SELECTED=128
GPU_ID=0
BASE_OUTPUT="./profiling_results"

# Task types to run
TASK_TYPES=("Summary" "Data2txt")

# ============================================
# Common run function
# ============================================
run_task() {
    local TASK=$1
    local OUTPUT_DIR="${BASE_OUTPUT}/${DETECTION_MODEL}_${DATA_MODEL}_${TASK}"

    echo "============================================"
    echo "  Detection model:  ${DETECTION_MODEL}"
    echo "  Data model:       ${DATA_MODEL}"
    echo "  Task type:        ${TASK}"
    echo "  Output:           ${OUTPUT_DIR}"
    echo "============================================"

    CUDA_VISIBLE_DEVICES=${GPU_ID} python run_profiled.py \
        --model_name ${DETECTION_MODEL} \
        --dataset_name ragtruth \
        --ragtruth_data_dir ${RAGTRUTH_DIR} \
        --ragtruth_model_filter ${DATA_MODEL} \
        --ragtruth_task_types ${TASK} \
        --batch_size ${BATCH_SIZE} \
        --str_layer ${STR_LAYER} \
        --lam ${LAM} \
        --lr ${LR} \
        --cos_temp ${COS_TEMP} \
        --ema_decay ${EMA_DECAY} \
        --init_num_epochs ${INIT_EPOCHS} \
        --aug_num_epochs ${AUG_EPOCHS} \
        --num_exemplars ${NUM_EXEMPLARS} \
        --num_selected_data ${NUM_SELECTED} \
        --component res \
        --profile_output_dir ${OUTPUT_DIR}/

    echo ""
    echo "  ${TASK} complete. Report: ${OUTPUT_DIR}/profiling_report.txt"
    echo ""
}

# ============================================
# Main
# ============================================
echo "================================================================"
echo "  TSV × RAGTruth Full Evaluation"
echo "  Detection model: ${DETECTION_MODEL}"
echo "  Data source:     ${DATA_MODEL}"
echo "  Tasks:           ${TASK_TYPES[*]}"
echo "  GPU:             ${GPU_ID}"
echo "================================================================"
echo ""

START_TIME=$(date +%s)

for i in "${!TASK_TYPES[@]}"; do
    TASK=${TASK_TYPES[$i]}
    echo "[$(($i+1))/${#TASK_TYPES[@]}] Starting ${TASK}..."
    run_task ${TASK}
done

END_TIME=$(date +%s)
TOTAL_TIME=$(($END_TIME - $START_TIME))

# ============================================
# Final Summary
# ============================================
echo "================================================================"
echo "  All runs complete!  Total time: ${TOTAL_TIME}s"
echo "================================================================"
echo ""
echo "  Detection model: ${DETECTION_MODEL}"
echo "  Data model:      ${DATA_MODEL}"
echo ""

for TASK in "${TASK_TYPES[@]}"; do
    DIR="${BASE_OUTPUT}/${DETECTION_MODEL}_${DATA_MODEL}_${TASK}"
    if [ -f "${DIR}/profiling_summary.json" ]; then
        AUROC=$(python3 -c "
import json
data = json.load(open('${DIR}/profiling_summary.json'))
best = -1
for p in data.get('phases', {}).values():
    a = p.get('best_auroc', -1)
    if a > best: best = a
print(f'{best:.4f}' if best > 0 else 'N/A')
" 2>/dev/null || echo "N/A")
        TIME=$(python3 -c "
import json
data = json.load(open('${DIR}/profiling_summary.json'))
print(f\"{data.get('total_time_seconds', 0):.1f}s\")
" 2>/dev/null || echo "N/A")
        echo "  ${TASK}:  AUROC=${AUROC}  Time=${TIME}  -> ${DIR}/"
    else
        echo "  ${TASK}:  (no results found)"
    fi
done

echo ""
echo "View full reports:"
for TASK in "${TASK_TYPES[@]}"; do
    echo "  cat ${BASE_OUTPUT}/${DETECTION_MODEL}_${DATA_MODEL}_${TASK}/profiling_report.txt"
done